import React, { Component } from 'react';
import * as headings from '../Styles/Text';
import styled from 'styled-components';
import * as color_palette from '../Styles/Colors';
import { makeStyles } from '@material-ui/core/styles';
import ExpansionPanel from '@material-ui/core/ExpansionPanel';
import ExpansionPanelSummary from '@material-ui/core/ExpansionPanelSummary';
import ExpansionPanelDetails from '@material-ui/core/ExpansionPanelDetails';
import Typography from '@material-ui/core/Typography';
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';
import Table from '@material-ui/core/Table';
import TableBody from '@material-ui/core/TableBody';
import TableCell from '@material-ui/core/TableCell';
import TableHead from '@material-ui/core/TableHead';
import TableRow from '@material-ui/core/TableRow';



const useStyles = makeStyles(theme => ({
  container:{
    maxWidth: '1200px',
    margin: '0 auto',
    paddingTop: '50px',
    paddingLeft: '15px',
    paddingRight: '15px'
  }
 
}));


export default function Indicator() {

    const classes = useStyles();
    return (
        
        <div className={classes.container}>
        <headings.H1>Indicator</headings.H1>


        <IndicatorContainer >
        <headings.H2>TB_PREV</headings.H2>
        <ExpansionPanel
             defaultExpanded="true"
        >
 
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Description</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
                <ChildContent>
                Proportion of ART patients who completed a standard course of 
                TB preventive therapy within the semiannual reporting period
                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>


       <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Numerator</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
                <FlexGrid>
                    <FlexGridHalfCol>
                    Number of ART patients who completed a course of TB preventive therapy during the 
                    reporting period (for continuous IPT programs, this includes the patients who have 
                    completed the first 6 months of isoniazid preventive therapy (IPT))
                    </FlexGridHalfCol>
                    <FlexGridHalfCol>
                    The numerator can be generated by counting the number of PLHIV on ART who are 
                    documented as having received at least six months of IPT or have completed another 
                    standard course of TB preventive therapy.
                    </FlexGridHalfCol>
                </FlexGrid>
       </ExpansionPanelDetails>
       </ExpansionPanel>


       <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Denominator</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
                <FlexGrid>
                    <FlexGridHalfCol>
                    Number of ART patients who are expected to complete a course of TB preventive 
                    therapy during the reporting period (for programs using continuous IPT, this 
                    includes only the patients who are scheduled to complete the first 6 months of 
                    therapy)
                    </FlexGridHalfCol>
                    <FlexGridHalfCol>
                    The denominator can be generated by counting the total number of patients who are scheduled 
                    to complete a course of TB preventive therapy (or at least 6 months of IPT for those who 
                    are on a prolonged or continuous regimen) in the semiannual reporting period.
                    </FlexGridHalfCol>
                </FlexGrid>
       </ExpansionPanelDetails>
       </ExpansionPanel>



       <ExpansionPanel
             defaultExpanded="true"
        >
 
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Indicator changes</ExpandTitle>
                <ExpandSubTitle>(MER 2.0 v2.2 to v2.3)</ExpandSubTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
                <ChildContent>
               <ChildList>
                   <li>Numerator disaggregates have been changed to capture Age/Sex by Type 
                   of TB preventive therapy (TPT) by ART Start.</li>
                   <li>Denominator disaggregates have been changed to capture Age/Sex by 
                   Type of TB preventive therapy (TPT) by ART Start.</li>
               </ChildList>
                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>


       <ExpansionPanel>
       <ExpansionPanelSummary
               
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Reporting level</ExpandTitle>
                <ExpandSubTitle>Facility</ExpandSubTitle>
        </ExpansionPanelSummary>
        </ExpansionPanel>

        <ExpansionPanel>
       <ExpansionPanelSummary
               
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Reporting frequency</ExpandTitle>
                <ExpandSubTitle>Semi-Annually</ExpandSubTitle>
        </ExpansionPanelSummary>
        </ExpansionPanel>


        <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>How to use</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
              <ChildContent>
              This indicator measures the performance of HIV programs in scaling up TB preventive therapy, 
              with the goal of preventing progression to active TB disease among PLHIV and decreasing ongoing 
              TB transmission in this population. As part of a cascade from TX_CURR to TB screening (captured 
              in TX_TB), this indicator will inform programs on the pace of scale-up, and the proportion will 
              allow for monitoring of cohorts through completion of therapy. Disaggregates on type of therapy 
              will inform programs on their relative use of different regimens, and the timing of ART will allow 
              the clinical cascade to focus on those who are newly entering care, which will better demonstrate 
              program performance, particularly in countries that have already provided TB preventive therapy for 
              many of their PLHIV in care.
                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>



       <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>How to collect</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
              <ChildContent>
              <ChildContent>The numerator can be generated by counting the number of PLHIV on ART who are documented as 
              having received at least six months of IPT or have completed another standard course of TB 
              preventive therapy. This should include the patients who completed a shorter alternative course, 
              such as 3 months of isoniazid and rifapentine (3HP), as well as those who are on prolonged or 
              continuous IPT who have completed their first 6 months of therapy during the semiannual reporting 
              period. <strong>Importantly, programs should ensure that patients on continuous therapy are counted only 
              once, and not repeated in future calculations.</strong></ChildContent>
              <ChildContent>
              The denominator can be generated by counting the total number of patients who are scheduled to 
              complete a course of TB preventive therapy (or at least 6 months of IPT for those who are on a 
              prolonged or continuous regimen) in the semiannual reporting period.
              </ChildContent>

              <strong>For IPT:</strong>
              <ChildList>
                   <li>Patients who are taking a standard 6-month course of IPT would be expected to complete therapy 
                   if they started IPT in the previous reporting period; therefore, all patients who started IPT at 
                   any time in the previous 6-month reporting period (i.e., the 6 months before the start of the 
                   current reporting period) should be included in the denominator. The few patients who start and 
                   complete IPT in the same reporting would also be included.</li>
                   <li>Patients who are taking prolonged (9- or 12-month) or continuous IPT would also be expected 
                   to complete the first 6 months of IPT if they started IPT in the previous reporting period; therefore, 
                   all patients who started prolonged or continuous IPT in the previous 6-month reporting period should 
                   be included. The few patients who start and complete 6 months of IPT in the same reporting would also 
                   be included.</li>
               </ChildList>


               <strong>For alternative regimens:</strong>
              <ChildList>
                   <li>Patients who are taking a 3-month regimen of isoniazid and rifapentine would be expected to 
                   complete therapy in this reporting period if they started on therapy at any time starting 3 months 
                   prior to the start of the current reporting period to 3 months prior to the end of the current 
                   reporting period; all such persons should be included in the denominator.</li>
                   <li>Patients who are taking a 4-month course of rifampicin would be expected to complete therapy 
                   in this reporting period if they were started on therapy at any time starting 4 months prior to 
                   the start of the current reporting period to 4 months prior to the end of the current reporting 
                   period; all such persons should be included in the denominator.</li>
               </ChildList>

               <ChildContent>
               These data elements can be collected from the ART register or from separate TB screening (presumptive TB) 
               or IPT registers.
              </ChildContent>


                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>



       <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>How to review for data quality</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
              <ChildContent>
              Only one disaggregation type is used for age (coarse disaggregations).
              Data Element ≥ subtotal of each of the disaggregations.
                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>


       <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>How to calculate annual total</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
              <ChildContent>
              When analyzing this data in conjunction with data on TB screening for ART patients (TX_TB), 
              it is preferred to analyze it as a snapshot indicator and use the result reported at Q4. 
              However, one could analyze the TB_PREV numerator independently of other data and sum the 
              results across Q2 and Q4 to calculate the total number of ART patients who completed a 
              course of TB preventive therapy during the fiscal year.
                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>


       <ExpansionPanel
             defaultExpanded="true"
        >
 
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Disaggregations</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
                <ChildContent>
               <ChildList>


               <TableTitle>Numerator Disaggregations:</TableTitle>

               <Table >
        <TableHead>
          <TableRow>
            <TableCell>Disaggregate Groups</TableCell>
            <TableCell>Disaggregates</TableCell>
          </TableRow>
        </TableHead>

        <TableBody>
        <TableRow>
            <TableCell>
            Age/Sex by Type of TB Preventive Therapy (TPT) by ART Start:[Required]</TableCell>
            <TableCell>
            <ChildList>
                   <li>IPT by newly enrolled on ART: &lt; 15 F/M, 15+ F/M, Unknown Age F/M</li>
                   <li>IPT by previously enrolled on ART: &lt;15 F/M, 15+ F/M, Unknown Age F/M</li>
                   <li>Alternative TPT regimen by newly enrolled on ART: &lt;15 F/M, 15+ F/M, Unknown Age F/M</li>
                   <li>Alternative TPT regimen by previously enrolled on ART: &lt;15 F/M, 15+ F/M, Unknown Age F/M</li>
            </ChildList>



            </TableCell>
          </TableRow>
        </TableBody>
        </Table>


        <TableTitle>Denominator Disaggregations:</TableTitle>
        <Table >
        <TableHead>
          <TableRow>
            <TableCell>Disaggregate Groups</TableCell>
            <TableCell>Disaggregates</TableCell>
          </TableRow>
        </TableHead>

        <TableBody>
        <TableRow>
            <TableCell>
           Age/Sex by Type of TB Preventive Therapy (TPT) by ART Start:[Required]</TableCell>
            <TableCell>
            <ChildList>
                   <li>IPT by newly enrolled on ART: &lt;15 F/M, 15+ F/M, Unknown Age F/M</li>
                   <li>IPT by previously enrolled on ART: &lt;15 F/M, 15+ F/M, Unknown Age F/M</li>
                   <li>Alternative TPT regimen by newly enrolled on ART: &lt;15 F/M, 15+ F/M, Unknown Age F/M</li>
                   <li>Alternative TPT regiment by previously enrolled on ART: &lt;15 F/M, 15+ F/M, Unknown Age F/M</li>
            </ChildList>



            </TableCell>
          </TableRow>
        </TableBody>
        </Table>



               </ChildList>
                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>






       <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Disaggregate descriptions & definitions</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
              <ChildContent>
             <strong>Type of TB Preventive Therapy (TPT) by ART Start Descriptions:</strong>
             <ChildList>
                   <li>IPT/Newly enrolled on ART: Among those who completed 6 months of IPT, the patients 
                   who started IPT and ART in the previous reporting period.</li>
                   <li>IPT/Previously enrolled on ART: Among those who completed 6 months of IPT, the patients 
                   who started IPT in the previous reporting period, but who started ART prior to the previous 
                   reporting period (i.e., patients who were on ART prior to the reporting period when they 
                   started IPT).</li>
                   <li>Alternative TPT regimen/Newly enrolled on ART: Among those who completed an alternative regimen 
                   (e.g., 3-month INH and rifapentine), the patients who started the regimen and ART in the current or 
                   the previous reporting period</li>
                   <li>Alternative TPT/Previously enrolled on ART: Among those who completed an alternative regimen 
                   (e.g., 3-month INH and rifapentine), the patients who started the regimen in the current or the 
                   previous reporting period, but started ART prior to previous reporting period</li>
            </ChildList>
                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>


       <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>PEPFAR-support definition</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
              <ChildContent>
             <strong>Standard definition of DSD and TA-SDI used.</strong>
             <ChildContent>
             <strong>Provision of key staff or commodities for routine HIV-related services includes: </strong>
             ongoing provision of critical re-occurring costs or commodities (such as ARVs, 
             TB preventive therapy and diagnostic/screening tests) or funding of salaries or provision 
             of Health Care Workers for HIV clinic services. Staff responsible for maintaining patient 
             records in both HIV and TB clinics are included in this category however staff responsible 
             for fulfilling reporting and routine M&E requirements are not included.
                </ChildContent>

                <ChildContent>
            <strong>Ongoing support for patients receiving routine HIV-related services includes:</strong> 
            training of HIV service providers, clinical mentoring and supportive supervision of staff at 
            HIV sites, infrastructure/renovation of facilities, support of HIV service data collection, 
            reporting, data quality, QI/QA of HIV services support, ARV and IPT consumption forecasting 
            and supply management, support of lab clinical.
                </ChildContent>


                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>

       <ExpansionPanel>
       <ExpansionPanelSummary
                expandIcon={<ExpandMoreIcon />}
                aria-controls="panel1a-content"
                id="panel1a-header"
               
              >
                <ExpandTitle>Guiding narrative questions</ExpandTitle>
              </ExpansionPanelSummary>
              <ExpansionPanelDetails>
              <ChildContent>
            
             <ChildList>
                   <li>Roughly what proportion of all PLHIV on treatment have already completed TB preventive 
                   therapy prior to this reporting period?</li>
                   <li>If TB preventive therapy was not provided to all PLHIV in care (and for who active TB 
                   disease was ruled out), what are the main reasons for limited scale-up?</li>
                   <li>Roughly what proportion of patients who received TB preventive therapy were treated with 
                   the 6-month (or longer) isoniazid regimen?</li>
                   <li>If completion rates were less than 85%, what are the main reasons why?</li>
                   <li>If less than 80% of newly enrolled PLHIV who screened negative for TB disease were 
                   started on TPT, what are the main reasons why?</li>
            </ChildList>
                </ChildContent>
       </ExpansionPanelDetails>
       </ExpansionPanel>



       </IndicatorContainer>


     </div>
    );
  
}


const IndicatorContainer = styled.div`
  background-color: #eeeeee;
  padding: 1em;
`;
const ChildContent = styled.p`
    margin:0;
    padding:0;
    padding-bottom: 1em;
    display: block;
    width: 100%;
`;
const ExpandTitle = styled.p`
    margin:0;
    padding:0;
    font-size: 1.2em;
    color: ${color_palette.SECONDARY_RED};
    font-weight: bold;
`;
const ExpandSubTitle = styled.span`
    margin-left: 1em;
    font-size: 1em;
    padding-top: 5px;
    font-weight: 300;
`;
const FlexGrid = styled.div`
    display: flex;
    justify-content: left;
    flex-wrap: wrap;
`;
const FlexGridHalfCol = styled.p`
    width: 45%;
    padding-right: 1em;

    @media (max-width: 768px){
        width: 100%;
    }
`;

const ChildList =styled.ul`
    margin-top:0;
    padding-top:0;
`;

const TableTitle = styled.h4`

`;

